Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "vm5" do |vm5|
    vm5.vm.hostname = "vm5"
    vm5.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 3165", auto_config: true
  end

  config.vm.define "vm6" do |vm6|
    vm6.vm.hostname = "vm6"
    vm6.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 3165", auto_config: true
  end
end
